// packages/frontend/src/lib/components/chat/MicButton.svelte
<script lang="ts">
import type { MessageKey } from "@drive-coding/core/i18n"
import { getI18n, getMic, getVoiceMode } from "$lib/context"
import type { VoiceModeState } from "$lib/view-models/derived/voice-mode.svelte"

const mic = getMic()
const voiceMode = getVoiceMode()
const t = getI18n().t

const ICONS: Record<VoiceModeState, string> = {
  idle: "🎙",
  recording: "⏺",
  transcribing: "🌀",
  thinking: "🌀",
  speaking: "🔊",
  cancelling: "✕",
}

// Map each VoiceMode state to its i18n label key
function statusKey(s: VoiceModeState): MessageKey {
  switch (s) {
    case "idle":         return "voiceMode.status.idle"
    case "recording":   return "voiceMode.status.recording"
    case "transcribing": return "voiceMode.status.transcribing"
    case "thinking":    return "voiceMode.status.thinking"
    case "speaking":    return "voiceMode.status.speaking"
    case "cancelling":  return "voiceMode.status.cancelling"
  }
}

const stateText = $derived(t(statusKey(voiceMode.state)))

function onClick() {
  if (voiceMode.state === "speaking" || voiceMode.state === "thinking") {
    voiceMode.cancel()
    return
  }
  if (voiceMode.state === "transcribing" || voiceMode.state === "cancelling") return
  // idle or recording
  void mic.toggle()
}
</script>

<div class="mic-container">
  <button
    class="mic-btn mic-{voiceMode.state}"
    onclick={onClick}
    disabled={voiceMode.state === "transcribing" || voiceMode.state === "cancelling"}
    aria-label={stateText}
  >
    <span class="icon">{ICONS[voiceMode.state]}</span>
  </button>
  {#if mic.error}
    <div class="mic-error" role="alert">{t(mic.error)}</div>
  {/if}
</div>

<style>
  .mic-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.4rem;
  }

  .mic-btn {
    width: 44px;
    height: 44px;
    border-radius: 50%;
    border: none;
    font-size: 20px;
    cursor: pointer;
    color: white;
    transition: transform 0.15s, box-shadow 0.2s, background 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    background: var(--accent);
    box-shadow: 0 2px 8px rgba(79, 140, 255, 0.4);
  }

  .mic-btn:hover:not(:disabled) {
    transform: scale(1.04);
  }

  .mic-btn:active:not(:disabled) {
    transform: scale(0.97);
  }

  .mic-btn:disabled {
    background: #2a2f3a;
    cursor: not-allowed;
    opacity: 0.7;
  }

  /* ── State colours ── */
  .mic-idle {
    background: var(--accent);
    box-shadow: 0 2px 8px rgba(79, 140, 255, 0.4);
  }

  .mic-recording {
    background: var(--recording);
    box-shadow: 0 2px 8px rgba(255, 79, 79, 0.5);
    animation: pulse 1.2s infinite;
  }

  .mic-transcribing {
    background: #8855ff;
    animation: rotate-slow 2s linear infinite;
  }

  .mic-thinking {
    background: var(--thinking);
    animation: rotate-slow 2s linear infinite;
  }

  .mic-speaking {
    background: var(--speaking);
    box-shadow: 0 0 14px rgba(79, 255, 138, 0.6);
    animation: glow 1.5s ease-in-out infinite alternate;
  }

  .mic-cancelling {
    background: #ff9933;
    animation: flash-fast 0.3s infinite;
  }

  /* ── Animations ── */
  @keyframes pulse {
    0%, 100% { box-shadow: 0 0 0 0 rgba(255, 79, 79, 0.5); }
    50%       { box-shadow: 0 0 0 10px rgba(255, 79, 79, 0); }
  }

  @keyframes rotate-slow {
    from { transform: rotate(0deg); }
    to   { transform: rotate(360deg); }
  }

  @keyframes glow {
    from { box-shadow: 0 0 8px rgba(79, 255, 138, 0.4); }
    to   { box-shadow: 0 0 20px rgba(79, 255, 138, 0.8); }
  }

  @keyframes flash-fast {
    0%, 100% { opacity: 1; }
    50%      { opacity: 0.4; }
  }

  .mic-error {
    font-size: 0.75rem;
    color: var(--recording);
    max-width: 200px;
    text-align: center;
    line-height: 1.3;
  }

  /* ── Icon (emoji) ── */
  .icon {
    display: flex;
    align-items: center;
    justify-content: center;
    font-style: normal;
  }
</style>

// docs/design-mockup/claude-design/2026-06-27/components/chat/MicButton.jsx
import React from "react";
import { Icon } from "../core/Icon.jsx";

/**
 * MicButton — the single large drive-first control (110px). One button drives
 * the whole voice loop; its color, icon, and animation encode the state machine:
 *   idle        accent,    mic
 *   recording   recording, mic     + halo pulse
 *   transcribing/thinking  thinking, spinner
 *   speaking    speaking,  volume  (dark glyph)
 *   cancelling  accent,    x       + fast flash
 * Disabled during transcribing/cancelling. A floating stop appears in speaking.
 */
const STATUS_TEXT = {
  idle: "לחצי על הכפתור כדי לדבר",
  recording: "מקליט…",
  transcribing: "מתמלל…",
  thinking: "מעבד…",
  speaking: "מקריא תשובה",
  cancelling: "מבטל…",
};

export function MicButton({ state = "idle", size = 110, onClick, onStop, showStatus = true, style }) {
  const disabled = state === "transcribing" || state === "cancelling";
  const isSpinning = state === "transcribing" || state === "thinking";

  const bg =
    state === "recording" ? "var(--recording)"
    : state === "speaking" ? "var(--speaking)"
    : isSpinning ? "var(--thinking)"
    : "var(--accent)";

  const fg = state === "speaking" ? "#111" : "#fff";
  const anim =
    state === "recording" ? "pulse-rec 1.2s infinite"
    : state === "cancelling" ? "flash-fast 0.3s infinite"
    : undefined;

  const iconName =
    state === "speaking" ? "volume-2"
    : isSpinning ? "loader"
    : state === "cancelling" ? "x"
    : "mic";

  const statusColor =
    state === "recording" ? "var(--recording)"
    : state === "speaking" ? "var(--speaking)"
    : isSpinning ? "var(--thinking)"
    : state === "cancelling" ? "var(--accent-hi)"
    : "var(--fg-dim)";

  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "0.75rem", ...style }}>
      <div style={{ position: "relative", display: "grid", placeItems: "center", minHeight: size + 20 }}>
        <button
          type="button"
          onClick={onClick}
          disabled={disabled}
          aria-label={STATUS_TEXT[state]}
          style={{
            width: size,
            height: size,
            borderRadius: "var(--radius-full)",
            border: "none",
            display: "grid",
            placeItems: "center",
            background: disabled && state === "cancelling" ? bg : bg,
            color: fg,
            cursor: disabled ? "not-allowed" : "pointer",
            boxShadow: "var(--shadow-mic)",
            transition: "transform var(--dur-fast) var(--ease), background var(--dur-base) var(--ease), box-shadow var(--dur-base) var(--ease)",
            animation: anim,
          }}
        >
          <Icon name={iconName} size={Math.round(size * 0.36)} strokeWidth={1.5} style={{ animation: isSpinning ? "spin 1s linear infinite" : undefined }} />
        </button>

        {state === "speaking" && (
          <button
            type="button"
            onClick={onStop}
            aria-label="עצור"
            style={{
              position: "absolute",
              insetInlineStart: `calc(50% + ${size / 2 + 4}px)`,
              bottom: 0,
              width: 36,
              height: 36,
              borderRadius: "var(--radius-full)",
              background: "var(--fg-muted)",
              color: "var(--bg)",
              border: "none",
              display: "grid",
              placeItems: "center",
              cursor: "pointer",
            }}
          >
            <Icon name="square" size={14} strokeWidth={2.5} />
          </button>
        )}
      </div>

      {showStatus && (
        <span style={{ fontSize: "var(--text-sm)", fontWeight: "var(--fw-medium)", color: statusColor }}>{STATUS_TEXT[state]}</span>
      )}
    </div>
  );
}
