// docs/design-mockup/claude-design/2026-06-27/components/core/Avatar.jsx
import React from "react";
import { Icon } from "./Icon.jsx";

/**
 * Avatar — chat-row identity chip. Maps a bubble `kind` to a Lucide icon and
 * a soft tinted background, exactly as the product does:
 *   user → user / accent     agent → sparkles / accent
 *   thought → brain / thinking   tool → wrench / accent
 */
const CFG = {
  user: { icon: "user", bg: "color-mix(in srgb, var(--accent) 18%, transparent)", fg: "var(--accent-hi)" },
  agent: { icon: "sparkles", bg: "color-mix(in srgb, var(--accent) 22%, transparent)", fg: "var(--accent-hi)" },
  thought: { icon: "brain", bg: "color-mix(in srgb, var(--thinking) 15%, transparent)", fg: "var(--thinking)" },
  tool: { icon: "wrench", bg: "color-mix(in srgb, var(--accent) 15%, transparent)", fg: "var(--accent-hi)" },
};

export function Avatar({ kind = "agent", size = 28, style }) {
  const c = CFG[kind] || CFG.agent;
  return (
    <span
      style={{
        flexShrink: 0,
        width: size,
        height: size,
        display: "grid",
        placeItems: "center",
        borderRadius: "var(--radius-full)",
        background: c.bg,
        color: c.fg,
        ...style,
      }}
    >
      <Icon name={c.icon} size={Math.round(size * 0.54)} strokeWidth={1.75} />
    </span>
  );
}

// packages/frontend/src/lib/components/chat/Avatar.svelte
<script lang="ts">
/**
 * Avatar — אווטאר Lucide לפי kind (C3).
 *
 * kind → צבע/רקע + אייקון (מוקאפ avatarCfg 1136-1147):
 *   user    → User  icon, accent-soft bg
 *   agent   → Sparkles icon, accent-soft bg
 *   thought → Brain icon, thinking-soft bg
 *   tool    → Wrench icon, accent-soft bg
 *
 * ─── redesign-5 (C3) ───
 */
import UserIcon from "@lucide/svelte/icons/user"
import SparklesIcon from "@lucide/svelte/icons/sparkles"
import BrainIcon from "@lucide/svelte/icons/brain"
import WrenchIcon from "@lucide/svelte/icons/wrench"

type AvatarKind = "user" | "agent" | "thought" | "tool"

interface Props {
  kind: AvatarKind
}

const { kind }: Props = $props()

const BG: Record<AvatarKind, string> = {
  user:    "color-mix(in srgb, var(--accent) 18%, transparent)",
  agent:   "color-mix(in srgb, var(--accent) 22%, transparent)",
  thought: "color-mix(in srgb, var(--thinking) 15%, transparent)",
  tool:    "color-mix(in srgb, var(--accent) 15%, transparent)",
}

const FG: Record<AvatarKind, string> = {
  user:    "var(--accent-hi)",
  agent:   "var(--accent-hi)",
  thought: "var(--thinking)",
  tool:    "var(--accent-hi)",
}
</script>

<span
  class="avatar shrink-0 size-7 grid place-items-center rounded-full"
  style="background:{BG[kind]}; color:{FG[kind]}"
>
  {#if kind === "user"}
    <UserIcon size={15} strokeWidth={1.75} />
  {:else if kind === "agent"}
    <SparklesIcon size={15} strokeWidth={1.75} />
  {:else if kind === "thought"}
    <BrainIcon size={15} strokeWidth={1.75} />
  {:else if kind === "tool"}
    <WrenchIcon size={15} strokeWidth={1.75} />
  {/if}
</span>
